# Generated by Django 4.1.4 on 2022-12-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
            ],
        ),
    ]
