# Generated by Django 4.1.4 on 2022-12-27 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0002_questionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.IntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb.empresa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb.questionario')),
            ],
        ),
    ]
