# Generated by Django 4.1.4 on 2022-12-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0004_alter_resposta_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.IntegerField(),
        ),
    ]
