# Generated by Django 4.1.4 on 2022-12-28 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0005_alter_resposta_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=10, max_digits=20)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb.questionario')),
            ],
        ),
    ]
