# Generated by Django 4.1.4 on 2022-12-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0006_valorreferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='adm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=999)),
            ],
        ),
    ]
