# Generated by Django 4.1.4 on 2023-01-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0008_delete_adm_empresa_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=10, max_digits=20)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb.questionario')),
            ],
        ),
    ]
