# Generated by Django 4.1.4 on 2023-01-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0009_targetgrafico'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoasPraticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='uploads/')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb.questionario')),
            ],
        ),
    ]
