# Generated by Django 4.1.4 on 2023-01-03 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0012_alter_boaspraticas_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boaspraticas',
            name='acesso',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='boaspraticas',
            name='boapratica',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='boaspraticas',
            name='empresa',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='boaspraticas',
            name='estrategiacircular',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wb.estrategiacircular'),
        ),
        migrations.AlterField(
            model_name='boaspraticas',
            name='fonte',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='boaspraticas',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='boaspraticas',
            name='segmento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wb.segmento'),
        ),
    ]
