# Generated by Django 4.1.4 on 2023-01-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0013_alter_boaspraticas_acesso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boaspraticas',
            name='imagem',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
