# Generated by Django 4.1.4 on 2023-01-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0014_alter_boaspraticas_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boaspraticas',
            name='segmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wb.segmento'),
        ),
    ]
