# Generated by Django 4.1.4 on 2023-01-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0015_alter_boaspraticas_segmento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoasPraticas',
        ),
        migrations.DeleteModel(
            name='EstrategiaCircular',
        ),
        migrations.DeleteModel(
            name='Segmento',
        ),
    ]
