# Generated by Django 4.1.4 on 2023-01-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0017_estrategiacircular_segmento_boaspraticas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoasPraticas',
        ),
    ]
