# Generated by Django 4.1.4 on 2023-01-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0018_delete_boaspraticas'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoasPraticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/')),
                ('empresa', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('boapratica', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('fonte', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('acesso', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('estrategiacircular', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wb.estrategiacircular')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb.questionario')),
                ('segmento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wb.segmento')),
            ],
        ),
    ]
