# Generated by Django 4.1.4 on 2023-01-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0023_estrategiacircular_segmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='boaspraticas',
            name='estrategiacircular',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wb.estrategiacircular'),
        ),
        migrations.AddField(
            model_name='boaspraticas',
            name='segmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wb.segmento'),
        ),
    ]
